//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test23demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Manufacture = new HashSet<Manufacture>();
            this.SpecificationMaterial = new HashSet<SpecificationMaterial>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int UnitId { get; set; }
    
        public virtual ICollection<Manufacture> Manufacture { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<SpecificationMaterial> SpecificationMaterial { get; set; }
    }
}
