//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test23demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationMaterial
    {
        public int Id { get; set; }
        public int SpecificationId { get; set; }
        public int MaterialId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
